from sqlalchemy import Boolean, Column, Integer, Numeric, String, Text, Date, TIMESTAMP, func
from app.database import Base


class SalesOrder(Base):
    __tablename__ = "sales_order"

    order_id = Column(String(36), primary_key=True)
    user_id = Column(String(36), nullable=False)
    fullfillment_center_id = Column(String(36), nullable=True)
    address_id = Column(String(36), nullable=True)
    cart_id = Column(String(36), nullable=True)
    subscription_id = Column(String(36), nullable=True)
    total_price = Column(Numeric(14, 2), nullable=True)
    price_without_delivery = Column(Numeric(14, 2), nullable=True)
    total_products_mrp = Column(Numeric(14, 2), nullable=True)
    delivery_charge = Column(Numeric(10, 2), nullable=False)
    cod_charges = Column(Numeric(10, 2), nullable=False)
    payment_method = Column(String(50), nullable=True)
    payment_type = Column(String(50), nullable=True)
    payment_status = Column(String(50), nullable=False, default="pending")
    paid_by_wallet = Column(Numeric(12, 2), nullable=False)
    rem_price = Column(Numeric(12, 2), nullable=False)
    reserve_amount = Column(Numeric(12, 2), nullable=False)
    avg_tax_per = Column(Numeric(5, 2), nullable=True)
    total_tax_price = Column(Numeric(12, 2), nullable=True)
    coupon_id = Column(String(36), nullable=True)
    coupon_code = Column(String(100), nullable=True)
    coupon_discount = Column(Numeric(10, 2), nullable=False)
    order_date = Column(TIMESTAMP, server_default=func.now())
    delivery_date = Column(Date, nullable=True)
    time_slot = Column(String(100), nullable=True)
    time_slot_discount = Column(Numeric(10, 2), nullable=False)
    dboy_id = Column(String(36), nullable=True)
    dboy_incentive = Column(Numeric(10, 2), nullable=False)
    del_partner_tip = Column(Numeric(10, 2), nullable=False)
    del_partner_instruction = Column(Text, nullable=True)
    order_status = Column(String(50), nullable=False, default="placed")
    user_signature = Column(String(500), nullable=True)
    out_for_delivery_datetime = Column(TIMESTAMP, nullable=True)
    complete_delivery_datetime = Column(TIMESTAMP, nullable=True)
    cancelling_reason = Column(Text, nullable=True)
    cancel_by_store = Column(Boolean, nullable=False)
    cancel_by = Column(String(50), nullable=True)
    refunded_amount = Column(Numeric(12, 2), nullable=False)
    si_sub_ref_no = Column(String(100), nullable=True)
    si_mer_charge_ref_no = Column(String(100), nullable=True)
    si_payment_flag = Column(Boolean, nullable=False)
    bank_ref_no = Column(String(100), nullable=True)
    bank_id = Column(String(36), nullable=True)
    approval_code = Column(String(100), nullable=True)
    reference_no = Column(String(100), nullable=True)
    deduction_amt = Column(Numeric(10, 2), nullable=False)
    deduction_date = Column(Date, nullable=True)
    notify_flag = Column(Boolean, nullable=False)
    notification_send_end = Column(Boolean, nullable=False)
    is_subscription = Column(Boolean, nullable=False)
    repeat_orders = Column(Integer, nullable=False)
    repeat_order_days = Column(Integer, nullable=True)
    total_delivery = Column(Integer, nullable=True)
    trail_id = Column(String(36), nullable=True)
    trail_discount = Column(Numeric(10, 2), nullable=False)
    aft_com_order_dis = Column(Numeric(10, 2), nullable=False)
    order_instruction = Column(Text, nullable=True)
    special_instruction = Column(Text, nullable=True)
    order_type = Column(String(50), nullable=True)
    is_offer_product = Column(Boolean, nullable=False)
    order_missing_status = Column(Boolean, nullable=False)
    platform = Column(String(50), nullable=True)
    browser = Column(String(100), nullable=True)
    group_id = Column(String(36), nullable=True)
    driver_photo = Column(String(500), nullable=True)
    driver_note = Column(Text, nullable=True)
    assign_to_driver_datetime = Column(TIMESTAMP, nullable=True)
    timeslot_updatedat = Column(TIMESTAMP, nullable=True)
    invoice_path = Column(String(500), nullable=True)
    pastorecentrder = Column(Boolean, nullable=False)
    created_at = Column(TIMESTAMP, server_default=func.now())
    updated_at = Column(TIMESTAMP, server_default=func.now(), onupdate=func.now())


class OrderLineItem(Base):
    __tablename__ = "order_line_item"

    order_line_id = Column(String(36), primary_key=True)
    order_id = Column(String(36), nullable=False)
    variant_id = Column(String(36), nullable=False)
    product_id = Column(String(36), nullable=True)
    quantity = Column(Integer, nullable=False)
    unit_price = Column(Numeric(12, 2), nullable=False)
    mrp = Column(Numeric(12, 2), nullable=True)
    total_price = Column(Numeric(14, 2), nullable=True)
    discount = Column(Numeric(10, 2), nullable=False)
    discount_per = Column(Numeric(5, 2), nullable=False)
    tax_per = Column(Numeric(5, 2), nullable=True)
    tax_amount = Column(Numeric(10, 2), nullable=True)
    is_subscription_item = Column(Boolean, nullable=False)
    original_qty = Column(Integer, nullable=True)
    dispatch_qty = Column(Integer, nullable=True)
    created_at = Column(TIMESTAMP, server_default=func.now())
